{
  "url": "https://api.github.com/repos/shap/shap/issues/132",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/132/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/132/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/132/events",
  "html_url": "https://github.com/shap/shap/issues/132",
  "id": 335426330,
  "node_id": "MDU6SXNzdWUzMzU0MjYzMzA=",
  "number": 132,
  "title": "UnicodeDecode error during installation",
  "user": {
    "login": "Nicolabo",
    "id": 5960799,
    "node_id": "MDQ6VXNlcjU5NjA3OTk=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5960799?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Nicolabo",
    "html_url": "https://github.com/Nicolabo",
    "followers_url": "https://api.github.com/users/Nicolabo/followers",
    "following_url": "https://api.github.com/users/Nicolabo/following{/other_user}",
    "gists_url": "https://api.github.com/users/Nicolabo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Nicolabo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Nicolabo/subscriptions",
    "organizations_url": "https://api.github.com/users/Nicolabo/orgs",
    "repos_url": "https://api.github.com/users/Nicolabo/repos",
    "events_url": "https://api.github.com/users/Nicolabo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Nicolabo/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2018-06-25T14:15:04Z",
  "updated_at": "2018-06-27T12:27:30Z",
  "closed_at": "2018-06-25T19:11:31Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Hi,\r\nI was trying to install `shap` package locally and on EC2.\r\n\r\nI was able to install it locally but on EC2 I got an error:\r\n\r\n```\r\n$ pip install shap\r\nCollecting shap\r\n  Using cached https://files.pythonhosted.org/packages/87/67/dc358c988a4527297e3a7f43d792088c7482338bfe2fa4fe67003228c601/shap-0.18.1.tar.gz\r\n    Complete output from command python setup.py egg_info:\r\n    'ascii' codec can't decode byte 0xc5 in position 9922: ordinal not in range(128)\r\n    WARNING: The C extension could not be compiled, sklearn tree models not supported.\r\n    Traceback (most recent call last):\r\n      File \"/tmp/pip-install-sqjxpliz/shap/setup.py\", line 51, in <module>\r\n        run_setup(True)\r\n      File \"/tmp/pip-install-sqjxpliz/shap/setup.py\", line 28, in run_setup\r\n        long_description = fh.read()\r\n      File \"/home/ubuntu/anaconda/envs/venv-conda-earlyalerts/lib/python3.6/encodings/ascii.py\", line 26, in decode\r\n        return codecs.ascii_decode(input, self.errors)[0]\r\n    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 9922: ordinal not in range(128)\r\n\r\n    During handling of the above exception, another exception occurred:\r\n\r\n    Traceback (most recent call last):\r\n      File \"<string>\", line 1, in <module>\r\n      File \"/tmp/pip-install-sqjxpliz/shap/setup.py\", line 55, in <module>\r\n        run_setup(False)\r\n      File \"/tmp/pip-install-sqjxpliz/shap/setup.py\", line 28, in run_setup\r\n        long_description = fh.read()\r\n      File \"/home/ubuntu/anaconda/envs/venv-conda-earlyalerts/lib/python3.6/encodings/ascii.py\", line 26, in decode\r\n        return codecs.ascii_decode(input, self.errors)[0]\r\n    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 9922: ordinal not in range(128)\r\n```\r\n\r\nI thought that it could be a problem with my EC2 instance. However, my colleague get the same error during installation on local machine. Do you know what's the problem?\r\n",
  "closed_by": {
    "login": "slundberg",
    "id": 3740613,
    "node_id": "MDQ6VXNlcjM3NDA2MTM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3740613?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/slundberg",
    "html_url": "https://github.com/slundberg",
    "followers_url": "https://api.github.com/users/slundberg/followers",
    "following_url": "https://api.github.com/users/slundberg/following{/other_user}",
    "gists_url": "https://api.github.com/users/slundberg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/slundberg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/slundberg/subscriptions",
    "organizations_url": "https://api.github.com/users/slundberg/orgs",
    "repos_url": "https://api.github.com/users/slundberg/repos",
    "events_url": "https://api.github.com/users/slundberg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/slundberg/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/132/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/132/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
