{
  "url": "https://api.github.com/repos/shap/shap/issues/1756",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/1756/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/1756/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/1756/events",
  "html_url": "https://github.com/shap/shap/issues/1756",
  "id": 788650319,
  "node_id": "MDU6SXNzdWU3ODg2NTAzMTk=",
  "number": 1756,
  "title": "Install error python 3.8 on Mac OS X Big Sur",
  "user": {
    "login": "qboy21",
    "id": 14353482,
    "node_id": "MDQ6VXNlcjE0MzUzNDgy",
    "avatar_url": "https://avatars.githubusercontent.com/u/14353482?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/qboy21",
    "html_url": "https://github.com/qboy21",
    "followers_url": "https://api.github.com/users/qboy21/followers",
    "following_url": "https://api.github.com/users/qboy21/following{/other_user}",
    "gists_url": "https://api.github.com/users/qboy21/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/qboy21/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/qboy21/subscriptions",
    "organizations_url": "https://api.github.com/users/qboy21/orgs",
    "repos_url": "https://api.github.com/users/qboy21/repos",
    "events_url": "https://api.github.com/users/qboy21/events{/privacy}",
    "received_events_url": "https://api.github.com/users/qboy21/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 12,
  "created_at": "2021-01-19T02:13:12Z",
  "updated_at": "2021-09-13T11:33:39Z",
  "closed_at": "2021-01-23T15:07:41Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Worked fine previously and now receive this error on pip install shap:\r\n\r\nCollecting shap\r\n  Using cached shap-0.38.1.tar.gz (352 kB)\r\n    ERROR: Command errored out with exit status 1:\r\n     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/vl/v_qqb7m90j78c3h1d_dyzx3m0000gn/T/pip-install-o84jijp9/shap_92982187dca64ab296328dcab301bb95/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/vl/v_qqb7m90j78c3h1d_dyzx3m0000gn/T/pip-install-o84jijp9/shap_92982187dca64ab296328dcab301bb95/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/vl/v_qqb7m90j78c3h1d_dyzx3m0000gn/T/pip-pip-egg-info-wn8rbuh_\r\n         cwd: /private/var/folders/vl/v_qqb7m90j78c3h1d_dyzx3m0000gn/T/pip-install-o84jijp9/shap_92982187dca64ab296328dcab301bb95/\r\n    Complete output (9 lines):\r\n    Traceback (most recent call last):\r\n      File \"<string>\", line 1, in <module>\r\n      File \"/private/var/folders/vl/v_qqb7m90j78c3h1d_dyzx3m0000gn/T/pip-install-o84jijp9/shap_92982187dca64ab296328dcab301bb95/setup.py\", line 25, in <module>\r\n        python_target = LooseVersion(get_config_var('MACOSX_DEPLOYMENT_TARGET'))\r\n      File \"/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/version.py\", line 304, in __init__\r\n        self.parse(vstring)\r\n      File \"/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/version.py\", line 312, in parse\r\n        components = [x for x in self.component_re.split(vstring)\r\n    TypeError: expected string or bytes-like object\r\n    ----------------------------------------\r\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.",
  "closed_by": {
    "login": "qboy21",
    "id": 14353482,
    "node_id": "MDQ6VXNlcjE0MzUzNDgy",
    "avatar_url": "https://avatars.githubusercontent.com/u/14353482?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/qboy21",
    "html_url": "https://github.com/qboy21",
    "followers_url": "https://api.github.com/users/qboy21/followers",
    "following_url": "https://api.github.com/users/qboy21/following{/other_user}",
    "gists_url": "https://api.github.com/users/qboy21/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/qboy21/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/qboy21/subscriptions",
    "organizations_url": "https://api.github.com/users/qboy21/orgs",
    "repos_url": "https://api.github.com/users/qboy21/repos",
    "events_url": "https://api.github.com/users/qboy21/events{/privacy}",
    "received_events_url": "https://api.github.com/users/qboy21/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/1756/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/1756/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
