{
  "url": "https://api.github.com/repos/shap/shap/issues/2144",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/2144/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/2144/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/2144/events",
  "html_url": "https://github.com/shap/shap/issues/2144",
  "id": 973599197,
  "node_id": "MDU6SXNzdWU5NzM1OTkxOTc=",
  "number": 2144,
  "title": "Categorical features in LGBM cause failure when using __call__ method of the TreeExplainer",
  "user": {
    "login": "mlisovyi",
    "id": 10157590,
    "node_id": "MDQ6VXNlcjEwMTU3NTkw",
    "avatar_url": "https://avatars.githubusercontent.com/u/10157590?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mlisovyi",
    "html_url": "https://github.com/mlisovyi",
    "followers_url": "https://api.github.com/users/mlisovyi/followers",
    "following_url": "https://api.github.com/users/mlisovyi/following{/other_user}",
    "gists_url": "https://api.github.com/users/mlisovyi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mlisovyi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mlisovyi/subscriptions",
    "organizations_url": "https://api.github.com/users/mlisovyi/orgs",
    "repos_url": "https://api.github.com/users/mlisovyi/repos",
    "events_url": "https://api.github.com/users/mlisovyi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mlisovyi/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 5,
  "created_at": "2021-08-18T12:12:51Z",
  "updated_at": "2023-06-03T02:06:06Z",
  "closed_at": "2023-06-03T02:06:06Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I bumped into the problem that when using the `__call__` method of the `TreeExplainer` on a LGBM model that uses categorical features, one gets an error like _\"ValueError: could not convert string to float:\"_.\r\n\r\nThe origin seem to be [this line](https://github.com/slundberg/shap/blob/89855e03d7e92ba0d2ec463c0505878f718664e3/shap/explainers/_tree.py#L206), i.e. one converts the input DataFrame into a numpy array and thus the info about categorical fetures (when those are defined by the types of features) get's lost, when the data are passed to the `shap_values` method [here](https://github.com/slundberg/shap/blob/89855e03d7e92ba0d2ec463c0505878f718664e3/shap/explainers/_tree.py#L211). The `shap_values` method itself works fine when the complete DataFrame is passed as input. \r\n\r\nBelow is a minimal reproducible example:\r\n```python\r\nimport lightgbm as lgb\r\nimport shap\r\n\r\n# train XGBoost model\r\nX, y = shap.datasets.adult()\r\n# add a dummy categorical variable\r\nX[\"Categorical\"] = \"A\"\r\nX[\"Categorical\"] = X[\"Categorical\"].astype(\"category\")\r\n# train a LGBM model with a categorical feature in the data\r\nmodel = lgb.LGBMClassifier().fit(X, y)\r\n\r\n# compute SHAP values\r\nexplainer = shap.TreeExplainer(model)\r\n# this works\r\n_ = explainer.shap_values(X.head(100))\r\n# this fails\r\n_ = explainer(X.head(100))\r\n```\r\n\r\nMy setup:\r\npython 3.8\r\nlightgbm 3.2.1\r\nshap 0.39.0",
  "closed_by": {
    "login": "dsgibbons",
    "id": 82195909,
    "node_id": "MDQ6VXNlcjgyMTk1OTA5",
    "avatar_url": "https://avatars.githubusercontent.com/u/82195909?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dsgibbons",
    "html_url": "https://github.com/dsgibbons",
    "followers_url": "https://api.github.com/users/dsgibbons/followers",
    "following_url": "https://api.github.com/users/dsgibbons/following{/other_user}",
    "gists_url": "https://api.github.com/users/dsgibbons/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dsgibbons/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dsgibbons/subscriptions",
    "organizations_url": "https://api.github.com/users/dsgibbons/orgs",
    "repos_url": "https://api.github.com/users/dsgibbons/repos",
    "events_url": "https://api.github.com/users/dsgibbons/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dsgibbons/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/2144/reactions",
    "total_count": 4,
    "+1": 4,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/2144/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
