{
  "url": "https://api.github.com/repos/shap/shap/issues/2248",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/2248/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/2248/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/2248/events",
  "html_url": "https://github.com/shap/shap/issues/2248",
  "id": 1041982158,
  "node_id": "I_kwDOBHDcK84-G2LO",
  "number": 2248,
  "title": "Unknown algorithm type passed: deep!",
  "user": {
    "login": "javirandor",
    "id": 17622558,
    "node_id": "MDQ6VXNlcjE3NjIyNTU4",
    "avatar_url": "https://avatars.githubusercontent.com/u/17622558?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/javirandor",
    "html_url": "https://github.com/javirandor",
    "followers_url": "https://api.github.com/users/javirandor/followers",
    "following_url": "https://api.github.com/users/javirandor/following{/other_user}",
    "gists_url": "https://api.github.com/users/javirandor/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/javirandor/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/javirandor/subscriptions",
    "organizations_url": "https://api.github.com/users/javirandor/orgs",
    "repos_url": "https://api.github.com/users/javirandor/repos",
    "events_url": "https://api.github.com/users/javirandor/events{/privacy}",
    "received_events_url": "https://api.github.com/users/javirandor/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2021-11-02T07:55:09Z",
  "updated_at": "2023-07-18T23:47:52Z",
  "closed_at": "2023-07-18T23:47:52Z",
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": null,
  "body": "According to the docs, when initializing an Explainer for a model using the class `shap.Explainer`, \"deep\" can be used as value for the attribute \"algorithm\" to create a DeepExplainer. However, when trying to do so the following error raises\r\n\r\n`Unknown algorithm type passed: deep!`\r\n\r\nI see that this is not implemented in the source code for the class. I guess it should be removed from doc or included in the initialization of the Explainer class.\r\n\r\nThanks.",
  "closed_by": {
    "login": "connortann",
    "id": 71127464,
    "node_id": "MDQ6VXNlcjcxMTI3NDY0",
    "avatar_url": "https://avatars.githubusercontent.com/u/71127464?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/connortann",
    "html_url": "https://github.com/connortann",
    "followers_url": "https://api.github.com/users/connortann/followers",
    "following_url": "https://api.github.com/users/connortann/following{/other_user}",
    "gists_url": "https://api.github.com/users/connortann/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/connortann/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/connortann/subscriptions",
    "organizations_url": "https://api.github.com/users/connortann/orgs",
    "repos_url": "https://api.github.com/users/connortann/repos",
    "events_url": "https://api.github.com/users/connortann/events{/privacy}",
    "received_events_url": "https://api.github.com/users/connortann/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/2248/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/2248/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
