{
  "url": "https://api.github.com/repos/shap/shap/issues/2466",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/2466/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/2466/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/2466/events",
  "html_url": "https://github.com/shap/shap/issues/2466",
  "id": 1185800031,
  "node_id": "I_kwDOBHDcK85Grd9f",
  "number": 2466,
  "title": "Error while replicating Keras-LSTM example",
  "user": {
    "login": "ishcha",
    "id": 51634188,
    "node_id": "MDQ6VXNlcjUxNjM0MTg4",
    "avatar_url": "https://avatars.githubusercontent.com/u/51634188?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ishcha",
    "html_url": "https://github.com/ishcha",
    "followers_url": "https://api.github.com/users/ishcha/followers",
    "following_url": "https://api.github.com/users/ishcha/following{/other_user}",
    "gists_url": "https://api.github.com/users/ishcha/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ishcha/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ishcha/subscriptions",
    "organizations_url": "https://api.github.com/users/ishcha/orgs",
    "repos_url": "https://api.github.com/users/ishcha/repos",
    "events_url": "https://api.github.com/users/ishcha/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ishcha/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 0,
  "created_at": "2022-03-30T03:02:08Z",
  "updated_at": "2022-03-30T03:52:20Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I am trying to replicate [Keras-LSTM DeepExplainer example](https://slundberg.github.io/shap/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.html). I am getting the following error when trying to compute the shap values: \r\n**This warning**: keras is no longer supported, please use tf.keras instead.\r\nYour TensorFlow version is newer than 2.4.0 and so graph support has been removed in eager mode and some static graphs may not be supported. See PR #1483 for discussion.\r\n**And this error**: \r\n`\r\nTypeError                                 Traceback (most recent call last)\r\n<ipython-input-27-ece205858809> in <module>\r\n      1 import shap\r\n      2 explainer = shap.DeepExplainer(model, x_train[:100])\r\n----> 3 shap_values = explainer.shap_values(x_test[:10])\r\n\r\n~/miniconda3/envs/mtq/lib/python3.8/site-packages/shap/explainers/_deep/__init__.py in shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)\r\n    122             were chosen as \"top\".\r\n    123         \"\"\"\r\n--> 124         return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)\r\n\r\n~/miniconda3/envs/mtq/lib/python3.8/site-packages/shap/explainers/_deep/deep_tf.py in shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)\r\n    306                 # run attribution computation graph\r\n    307                 feature_ind = model_output_ranks[j,i]\r\n--> 308                 sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)\r\n309 \r\n    310                 # assign the attributions to the right part of the output arrays\r\n\r\n~/miniconda3/envs/mtq/lib/python3.8/site-packages/shap/explainers/_deep/deep_tf.py in run(self, out, model_inputs, X)\r\n    363 \r\n    364                 return final_out\r\n--> 365             return self.execute_with_overridden_gradients(anon)\r\n    366 \r\n    367     def custom_grad(self, op, *grads):\r\n\r\n~/miniconda3/envs/mtq/lib/python3.8/site-packages/shap/explainers/_deep/deep_tf.py in execute_with_overridden_gradients(self, f)\r\n    399         # define the computation graph for the attribution values using a custom gradient-like computation\r\n    400         try:\r\n--> 401             out = f()\r\n    402         finally:\r\n    403             # reinstate the backpropagatable check\r\n\r\n~/miniconda3/envs/mtq/lib/python3.8/site-packages/shap/explainers/_deep/deep_tf.py in anon()\r\n    356                     shape = list(self.model_inputs[i].shape)\r\n    357                     shape[0] = -1\r\n--> 358                     data = X[i].reshape(shape)\r\n    359                     v = tf.constant(data, dtype=self.model_inputs[i].dtype)\r\n    360                     inputs.append(v)\r\n\r\n_**TypeError: 'NoneType' object cannot be interpreted as an integer**_\r\n`\r\n\r\nI have checked out the PR#1483, but couldn't find a relevant fix there. Please suggest on what tensorflow, keras, and shap versions are needed to successfully replicate the example. ",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/2466/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/2466/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
