{
  "url": "https://api.github.com/repos/shap/shap/issues/2759",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/2759/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/2759/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/2759/events",
  "html_url": "https://github.com/shap/shap/issues/2759",
  "id": 1445379694,
  "node_id": "I_kwDOBHDcK85WJr5u",
  "number": 2759,
  "title": "Problem with DeepExplainer. Getting Error when passing background images.",
  "user": {
    "login": "mehrdadasadiut",
    "id": 111504275,
    "node_id": "U_kgDOBqVrkw",
    "avatar_url": "https://avatars.githubusercontent.com/u/111504275?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mehrdadasadiut",
    "html_url": "https://github.com/mehrdadasadiut",
    "followers_url": "https://api.github.com/users/mehrdadasadiut/followers",
    "following_url": "https://api.github.com/users/mehrdadasadiut/following{/other_user}",
    "gists_url": "https://api.github.com/users/mehrdadasadiut/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mehrdadasadiut/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mehrdadasadiut/subscriptions",
    "organizations_url": "https://api.github.com/users/mehrdadasadiut/orgs",
    "repos_url": "https://api.github.com/users/mehrdadasadiut/repos",
    "events_url": "https://api.github.com/users/mehrdadasadiut/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mehrdadasadiut/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 0,
  "created_at": "2022-11-11T12:05:30Z",
  "updated_at": "2022-11-11T12:06:17Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Hello.\r\nHere is my pre-trained model summary. I get errors when using DeepExplainer.  I am using 503 test backgrounds for computing Shap values.\r\nAnyone can give a hand? Thanks.\r\nError : Layer \"sequential_1\" expects 1 input(s), but it received 503 input tensors. Inputs received: [<tf.Tensor: shape=(1, 300, 300, 3), dtype=float64, numpy=\r\n\r\nModel Summary: Model: \"sequential_1\"\r\n_________________________________________________________________\r\n Layer (type)                Output Shape              Param #   \r\n=================================================================\r\n conv2d_3 (Conv2D)           (None, 300, 300, 32)      896       \r\n                                                                 \r\n max_pooling2d_3 (MaxPooling  (None, 150, 150, 32)     0         \r\n 2D)                                                             \r\n                                                                 \r\n conv2d_4 (Conv2D)           (None, 150, 150, 64)      18496     \r\n                                                                 \r\n max_pooling2d_4 (MaxPooling  (None, 75, 75, 64)       0         \r\n 2D)                                                             \r\n                                                                 \r\n conv2d_5 (Conv2D)           (None, 75, 75, 32)        18464     \r\n                                                                 \r\n max_pooling2d_5 (MaxPooling  (None, 37, 37, 32)       0         \r\n 2D)                                                             \r\n                                                                 \r\n flatten_1 (Flatten)         (None, 43808)             0         \r\n                                                                 \r\n dense_3 (Dense)             (None, 64)                2803776   \r\n                                                                 \r\n dropout_2 (Dropout)         (None, 64)                0         \r\n                                                                 \r\n dense_4 (Dense)             (None, 32)                2080      \r\n                                                                 \r\n dropout_3 (Dropout)         (None, 32)                0         \r\n                                                                 \r\n dense_5 (Dense)             (None, 6)                 198       \r\n                                                                 \r\n=================================================================\r\nTotal params: 2,843,910\r\nTrainable params: 2,843,910\r\nNon-trainable params: 0",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/2759/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/2759/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
