{
  "url": "https://api.github.com/repos/shap/shap/issues/2829",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/2829/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/2829/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/2829/events",
  "html_url": "https://github.com/shap/shap/issues/2829",
  "id": 1526534892,
  "node_id": "I_kwDOBHDcK85a_RLs",
  "number": 2829,
  "title": "explain models generated using MLJAR",
  "user": {
    "login": "dbrami",
    "id": 163803,
    "node_id": "MDQ6VXNlcjE2MzgwMw==",
    "avatar_url": "https://avatars.githubusercontent.com/u/163803?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dbrami",
    "html_url": "https://github.com/dbrami",
    "followers_url": "https://api.github.com/users/dbrami/followers",
    "following_url": "https://api.github.com/users/dbrami/following{/other_user}",
    "gists_url": "https://api.github.com/users/dbrami/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dbrami/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dbrami/subscriptions",
    "organizations_url": "https://api.github.com/users/dbrami/orgs",
    "repos_url": "https://api.github.com/users/dbrami/repos",
    "events_url": "https://api.github.com/users/dbrami/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dbrami/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2023-01-10T00:09:29Z",
  "updated_at": "2023-01-14T19:09:04Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Hello,\r\nI have a multi-class category model made using MLJAR (\"perform\").\r\nWhen I try to understand, i get the following:\r\n```\r\n---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\nCell In[8], line 2\r\n      1 # get shap values\r\n----> 2 explainer = shap.Explainer(automl)\r\n\r\nFile /usr/local/miniconda/lib/python3.9/site-packages/shap/explainers/_explainer.py:173, in Explainer.__init__(self, model, masker, link, algorithm, output_names, feature_names, linearize_link, seed, **kwargs)\r\n    169             algorithm = \"permutation\"\r\n    171     # if we get here then we don't know how to handle what was given to us\r\n    172     else:\r\n--> 173         raise TypeError(\"The passed model is not callable and cannot be analyzed directly with the given masker! Model: \" + str(model))\r\n    175 # build the right subclass\r\n    176 if algorithm == \"exact\":\r\n\r\nTypeError: The passed model is not callable and cannot be analyzed directly with the given masker! Model: AutoML(explain_level=2, ml_task='multiclass_classification')\r\n```\r\n\r\nAny idea how to solve and understand?",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/2829/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/2829/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
