{
  "url": "https://api.github.com/repos/shap/shap/issues/399",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/399/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/399/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/399/events",
  "html_url": "https://github.com/shap/shap/issues/399",
  "id": 401177712,
  "node_id": "MDU6SXNzdWU0MDExNzc3MTI=",
  "number": 399,
  "title": "question about 'algorithm' file not found",
  "user": {
    "login": "yanlele9654",
    "id": 46334781,
    "node_id": "MDQ6VXNlcjQ2MzM0Nzgx",
    "avatar_url": "https://avatars.githubusercontent.com/u/46334781?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/yanlele9654",
    "html_url": "https://github.com/yanlele9654",
    "followers_url": "https://api.github.com/users/yanlele9654/followers",
    "following_url": "https://api.github.com/users/yanlele9654/following{/other_user}",
    "gists_url": "https://api.github.com/users/yanlele9654/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/yanlele9654/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/yanlele9654/subscriptions",
    "organizations_url": "https://api.github.com/users/yanlele9654/orgs",
    "repos_url": "https://api.github.com/users/yanlele9654/repos",
    "events_url": "https://api.github.com/users/yanlele9654/events{/privacy}",
    "received_events_url": "https://api.github.com/users/yanlele9654/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 5,
  "created_at": "2019-01-21T03:14:10Z",
  "updated_at": "2019-01-22T20:43:47Z",
  "closed_at": "2019-01-21T18:39:01Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "when i am try to download the shap via pip install shap\r\nI found that I have the following errors\r\nIn file included from shap/_cext.cc:5:\r\n    shap/tree_shap.h:8:10: fatal error: 'algorithm' file not found\r\n    #include <algorithm>\r\n             ^~~~~~~~~~~\r\n    1 warning and 1 error generated.\r\n    error: command 'gcc' failed with exit status 1\r\n\r\ncould any one tell me what should I do ",
  "closed_by": {
    "login": "slundberg",
    "id": 3740613,
    "node_id": "MDQ6VXNlcjM3NDA2MTM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3740613?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/slundberg",
    "html_url": "https://github.com/slundberg",
    "followers_url": "https://api.github.com/users/slundberg/followers",
    "following_url": "https://api.github.com/users/slundberg/following{/other_user}",
    "gists_url": "https://api.github.com/users/slundberg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/slundberg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/slundberg/subscriptions",
    "organizations_url": "https://api.github.com/users/slundberg/orgs",
    "repos_url": "https://api.github.com/users/slundberg/repos",
    "events_url": "https://api.github.com/users/slundberg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/slundberg/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/399/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/399/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
